name: nix-build

on:
  push:
    branches: master
  pull_request:
    branches: master

permissions:
  contents: read

jobs:
  nix-build:
    name: Nix on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up Nix
        uses: cachix/install-nix-action@v22
        id: setup
          
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y x11proto-xext-dev libx11-dev xorg-dev freeglut3-dev

      - name: Build
        run: nix build .#examples
